name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true

      - run: go mod download

      - name: Build
        run: go build ./domain/... ./infra/... ./usecase/... ./handler/...

      - name: Test
        run: go test -v ./

      - name: Vet
        run: go vet ./...
